---
title: "WorkFile"
author: "Trevor Freeland"
date: "May 30, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stargazer)
library(lme4)
library(tidyr)
library(MASS)
library(pscl)
library(HLMdiag)
library(gridExtra)

model.counts <- source("http://math.carleton.edu/Chihara/Stats345/Count_Function.R")$value
```

##Data Cleanup

```{r}
VideoGames <- read.csv("VideoGames.csv") #16719 cases

#Converting year of release and user score to numerics from factors.
VideoGames$Year_of_Release <- as.numeric(as.character(VideoGames$Year_of_Release))
VideoGames$User_Score <- as.numeric(as.character(VideoGames$User_Score))

#Only using complete cases
VideoGames <- na.omit(VideoGames) #6894 full cases. 

#Some ratings only had 1 or 0 games in our narrowed down data, so converting them to no rating level.
VideoGames$Rating2 <- as.factor(ifelse(VideoGames$Rating %in% c("E", "E10+", "M", "T"), as.character(VideoGames$Rating), "No Rating"))

#Create "Other" category for publishers/developers that worked on 10 games or less
Publishers <- VideoGames %>% group_by(Publisher) %>% summarize(n = n())
Publishers$Publisher2 <- as.factor(ifelse(Publishers$n > 10, as.character(Publishers$Publisher), "Other"))
VideoGames2 <- merge(VideoGames, Publishers[,c(1,3)], by.x = "Publisher", by.y = "Publisher")

Developers <- VideoGames %>% group_by(Developer) %>% summarize(n = n())
Developers$Developer2 <- as.factor(ifelse(Developers$n > 10, as.character(Developers$Developer), "Other"))
VideoGames2 <- merge(VideoGames2, Developers[,c(1,3)], by.x = "Developer", by.y = "Developer")

#Scaling Critic score to be on the same scale as user score and scaling time to start at 0 in 1985. 
VideoGames2$Critic_Score2 <- VideoGames2$Critic_Score/10
VideoGames2$Year2 <- VideoGames2$Year_of_Release - 1985
```

##Some EDA

```{r}
#Examing units sold for different Genres
edaData <- VideoGames %>% gather(Region, Sales, c("NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"))
ggplot(edaData, aes(x = Genre, y = Sales, fill = Region)) + geom_bar(stat = "identity")

#Checking to see if we should treat platform as a random effect or fixed effect. 
p1 <- ggplot(VideoGames2, aes(x = Platform, y = NA_Sales)) + geom_boxplot() + 
  ggtitle("Figure 1a: North America Sales by Platform") + 
  labs(x = "Video Game Platform", y = "NA Sales")

#Checking to see if we should treat publisher as a random or fixed effect. 
VideoGamesPub <- subset(VideoGames2, subset = Publisher2 %in% c("Activision", "Bethesda Softworks", "Electronic Arts", "Konami Digital Entertainment", "Microsoft Game Studios", "Nintendo", "Sega", "Sony Computer Entertainment", "Square Enix", "Ubisoft"))
p2 <- ggplot(VideoGamesPub, aes(x = Publisher2, y = NA_Sales)) + geom_boxplot() + 
  #theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_x_discrete(labels = c("Activision", "Bethesda", "EA", "Konami", "Microsoft", "Nintendo", "Sega", "Sony", "Square Enix", "Ubisoft")) +
  ggtitle("Figure 1b: North America Sales by Publisher") + 
  labs(x = "Video Game Publisher", y = "NA Sales")

grid.arrange(p1, p2, nrow = 1)
```

```{r}
na.hurdle <- hurdle((NA_Sales*100)~Platform+Year2+Genre+User_Score+Critic_Score2+Rating2+Publisher2, data = VideoGames2)
summary(na.hurdle)

na.hurdle2 <- hurdle((NA_Sales*100)~Platform+Genre+User_Score+Critic_Score2+Rating2+Publisher2|Platform+Year2+Genre+User_Score+Critic_Score2+Rating2, data = VideoGames2)
AIC(na.hurdle); AIC(na.hurdle2)
#274714.1; 274787.6

na.hurdle3 <- hurdle((NA_Sales*100)~Platform+Year2+Genre+User_Score+Critic_Score2+Rating2+Publisher2, data = VideoGames2, dist = "negbin")
AIC(na.hurdle); AIC(na.hurdle3)
summary(na.hurdle3)

na.hurdle4 <-  hurdle((NA_Sales*100)~Platform+Year2+Genre+User_Score+Critic_Score2+Rating2+Publisher2 | Platform+Year2+Genre+User_Score+Critic_Score2+Rating2, data = VideoGames2, dist = "negbin")
AIC(na.hurdle3); AIC(na.hurdle4)
#56941.65; 57015.14

eu.hurdle <- hurdle((EU_Sales*100)~Platform+Year2+Genre+User_Score+Critic_Score2+Rating2+Publisher2, data = VideoGames2, dist = "negbin")
summary(eu.hurdle)

eu.hurdle2 <- hurdle((EU_Sales*100)~Platform+Year2+Genre+User_Score+Critic_Score2+Rating2+Publisher2 | Platform+Year2+Genre+Critic_Score2+Rating2, data = VideoGames2, dist = "negbin")
AIC(eu.hurdle); AIC(eu.hurdle2)
#48923.33; 49174.7
```

```{r, eval = FALSE}
#Below here we tried fitting a zeroinflation model and different random effects models. 
#We ran into troubles being able to run the zeroinflated model with such large factor variables
#We also saw that our hurdle model did very well on prediction counts. 

na.sales <- zeroinfl((NA_Sales*100)~Year_of_Release+Genre+Critic_Score+User_Score+Rating2+Platform, data = VideoGames2, dist = "negbin")

VideoGames3 <- VideoGames2 %>% filter(NA_Sales > 0)
VideoGames4 <- VideoGames2 %>% filter(EU_Sales > 0)

na.sales2 <- glmer((NA_Sales*100)~Year2 + Genre + Critic_Score2+User_Score+Rating2 + (1|Publisher2) + (1|Platform), data = VideoGames3, family = poisson)


eu.sales <- glmer((EU_Sales*100)~Year2 + Genre + Critic_Score2+User_Score+Rating2 + (1|Publisher2) + (1|Platform), data = VideoGames4, family = poisson)

#After deliberation we believe that it would be best/make most sense to use a hurdle model. 

stargazer(na.sales2, eu.sales, type='text')
```

```{r, eval = FALSE}
x <- HLMresid(na.sales2, level="marginal", standardize = TRUE)

#standardized marginal: curvature? outliers?

plot(x ~ fitted(na.sales2), data = VideoGames2)
abline(h= 0)

#residuals in order of observation number

plot(x)
abline(h = 0)

#standardized conditional
x2 <- HLMresid(na.sales2, level = 1, standardize = TRUE)

#constant variance? outliers?
plot(fitted(na.sales2), x2)
abline(h= 0)

#in order of observation number
plot(x2)

cd <- cooks.distance(na.sales2)
plot(cd, type = "h") #using base R plot
dotplot_diag(cd, cutoff="internal", name="cooks.distance")
```



